version: "3.9"

networks:
  libjaypea_network:
    driver: bridge
    name: libjaypea_network

volumes:
  postgresql-data:

services:
      
  libjaypea-db:
    container_name: libjaypea-db
    image: postgres:13
    environment:
      - POSTGRES_DB=webservice
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=abc123
      # - POSTGRES_HOST_AUTH_METHOD=md5
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - libjaypea_network

  libjaypea-compile:
    container_name: libjaypea-compile
    build:
      context: ./
      dockerfile: ./dockerfile.compile
    volumes:
      - ./:/opt/libjaypea

  libjaypea:
    depends_on:
      libjaypea-compile:
        condition: service_completed_successfully
      libjaypea-db:
        condition: service_started
    container_name: libjaypea
    build:
      context: ./
      dockerfile: ./dockerfile
      args:
        DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/opt/libjaypea
      - ./data:/var/lib/pgsql/data
    image: libjaypea:latest
    ports:
      - 10080:10080
      - 10443:10443
      - 11000:11000
    networks:
      - libjaypea_network
